-- New Buildings module -- for clients managed as a whole building (multiple
-- flats) rather than a single apartment: per-flat common charges, generator/
-- fuel/other expenses against a supplier directory, and a running cash
-- ledger for the building (collections in, expenses out).
create table if not exists buildings (
  id uuid primary key default uuid_generate_v4(),
  client_id uuid not null references clients(id) on delete cascade,
  name text not null,
  address text,
  notes text,
  created_at timestamptz default now()
);
create index if not exists idx_buildings_client on buildings(client_id);

create table if not exists building_units (
  id uuid primary key default uuid_generate_v4(),
  building_id uuid not null references buildings(id) on delete cascade,
  unit_label text not null,
  owner_name text,
  contact_phone text,
  common_charge_amount numeric(10, 2) not null default 0,
  is_active boolean not null default true,
  created_at timestamptz default now()
);
create index if not exists idx_building_units_building on building_units(building_id);

-- One row per flat per billing period -- generated by the "Generate This
-- Month's Common Charges" action, which is safe to click more than once
-- (skips units that already have a charge for the period).
create table if not exists building_charges (
  id uuid primary key default uuid_generate_v4(),
  building_id uuid not null references buildings(id) on delete cascade,
  unit_id uuid not null references building_units(id) on delete cascade,
  period text not null,
  amount numeric(10, 2) not null,
  status text not null default 'due' check (status in ('due', 'paid')),
  due_date date,
  paid_at timestamptz,
  created_at timestamptz default now(),
  unique (unit_id, period)
);
create index if not exists idx_building_charges_building on building_charges(building_id);

-- Global directory (not per-building) -- the same generator/fuel/maintenance
-- suppliers tend to service multiple buildings.
create table if not exists building_suppliers (
  key text primary key,
  name text not null,
  category text,
  contact_phone text,
  contact_email text,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz default now()
);

-- Manually logged -- generator/fuel runs happen roughly twice a month but
-- need a human to enter the actual amount each time, unlike common charges
-- which are a fixed recurring number.
create table if not exists building_expenses (
  id uuid primary key default uuid_generate_v4(),
  building_id uuid not null references buildings(id) on delete cascade,
  category text not null check (category in ('generator', 'fuel', 'maintenance', 'other')),
  supplier_key text references building_suppliers(key),
  description text,
  amount numeric(10, 2) not null,
  expense_date date not null default current_date,
  created_by uuid references staff(id),
  created_at timestamptz default now()
);
create index if not exists idx_building_expenses_building on building_expenses(building_id);

alter table buildings enable row level security;
alter table building_units enable row level security;
alter table building_charges enable row level security;
alter table building_suppliers enable row level security;
alter table building_expenses enable row level security;

create policy "staff full access on buildings"
  on buildings for all
  using (auth_staff_role() is not null)
  with check (auth_staff_role() is not null);

create policy "staff full access on building_units"
  on building_units for all
  using (auth_staff_role() is not null)
  with check (auth_staff_role() is not null);

create policy "staff full access on building_charges"
  on building_charges for all
  using (auth_staff_role() is not null)
  with check (auth_staff_role() is not null);

create policy "staff full access on building_suppliers"
  on building_suppliers for all
  using (auth_staff_role() is not null)
  with check (auth_staff_role() is not null);

create policy "staff full access on building_expenses"
  on building_expenses for all
  using (auth_staff_role() is not null)
  with check (auth_staff_role() is not null);

insert into role_section_access (role_key, section)
select 'owner', 'buildings'
where not exists (
  select 1 from role_section_access where role_key = 'owner' and section = 'buildings'
);
